"""add note to moodentry

Revision ID: b54e787b627c
Revises: 2bb2f6cb6f5a
Create Date: 2026-09-25 15:34:38.187006

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54e787b627c'
down_revision: Union[str, Sequence[str], None] = '912ba19af7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodentry', sa.Column('not2e', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moodentry', 'not2e')
    # ### end Alembic commands ###
