"""rollback

Revision ID: cba2c5dca5f2
Revises: b54e787b627c
Create Date: 2026-09-25 15:45:23.717983

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cba2c5dca5f2'
down_revision: Union[str, Sequence[str], None] = 'b54e787b627c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodentry', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('moodentry', 'not2e')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodentry', sa.Column('not2e', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('moodentry', 'note')
    # ### end Alembic commands ###
